"""
Activity Planner Agent

Responsible for:
- Generating daily/weekly activity ideas
- Using child age, interests and context
- Refining plans in a loop until quality constraints are met
"""

class ActivityPlannerAgent:
    def __init__(self, tools=None, memory=None):
        self.tools = tools or {}
        self.memory = memory

    def plan_activities(self, age_months: int, constraints: dict | None = None) -> list[str]:
        """
        Placeholder implementation.
        Returns a small hard-coded list for now.
        """
        constraints = constraints or {}
        return [
            f"Simple placeholder activity for {age_months} months (will be generated by LLM later)."
        ]
